cpsw_yaml_keytrack_tst: added test to track unrecognized YAML keys.

diff --git a/src/test/makefile b/src/test/makefile
--- a/src/test/makefile
+++ b/src/test/makefile
@@ -115,6 +115,10 @@ cpsw_aligned_mmio_tst_SRCS= cpsw_aligned_mmio_tst.cc
 cpsw_aligned_mmio_tst_LIBS= $(CPSW_LIBS)
 TESTPROGRAMS              += cpsw_aligned_mmio_tst
 
+cpsw_yaml_keytrack_tst_SRCS= cpsw_yaml_keytrack_tst.cc
+cpsw_yaml_keytrack_tst_LIBS= $(CPSW_LIBS)
+TESTPROGRAMS              += cpsw_yaml_keytrack_tst
+
 
 TEST_AXIV_YES=
 TEST_AXIV_NO =cpsw_axiv_udp_tst
@@ -175,5 +179,11 @@ cpsw_enum_tst_run:      RUN_OPTS='-y cpsw_enum_tst.yaml' '-Y cpsw_enum_tst.yaml'
 cpsw_command_tst_run:   RUN_OPTS='-y cpsw_command_tst.yaml' '-Y cpsw_command_tst.yaml'
 
 rssi_tst_run:           RUN_OPTS='-s500' '-n30000 -G2' '-n30000 -L1'
+
+cpsw_yaml_keytrack_tst_run: cpsw_yaml_keytrack_tst
+	if ./$^ 2>&1 > /dev/null | grep -v 'Warning.*Junk$$' ; then \
+		echo "TEST $^ FAILED; unexpected keys found"; \
+		exit 1; \
+	fi
 
 #cpsw_netio_tst: udpsrv
